version: "3.9"

services:
  model:
    container_name: simple_docker_python
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/home/model
#    tty : true
    environment:
      TZ: Asia/Seoul
